Jasmin= [
    "<br>",
    "Agente:Jasmin",
    "Nome real:Maria Flor",
    "Status: Em missão",
    "Anotações: Maria flor é mestre em Biologia e ex-pesquisadora da UFRJ, ela foi levada ao nosso departamento, por",
    "possível envolvimento com a ex-cidadã Camila Botelho, seu histórico e antecedentes criminais foram checados, assim como",
    "cartas e ligações, não foi encontrado nenhum envolvimento Terrorista, Exoterrorista ou com Movimentos Progressistas",
    "Maria Flor apresentava um ótimo potencial de pesquisa para anomalias e atividades paranormais,",
    "assim então sendo contratada para trabalhar conosco nas missões",
    "Digite o sobrenome do usuário ou agente seguido do log para mais informações:",
    "Exemplo Agente Souza => Souza Log 0001",
    "<br>"
]

Camila = [
"<br>",
"██████████████████████████████████████████",
"         DEMP — REGISTRO CLASSIFICADO         ",
"██████████████████████████████████████████",
"<br>",
"ARQUIVO Nº 0047-B",
"<br>",
"IDENTIDADE ORIGINAL",
"——————————————————",
"Nome: Camila Botelho",
"Nascimento: [SUPRIMIDO]",
"Filiação: [SUPRIMIDO]",
"<br>",
"IDENTIDADE ATUAL",
"——————————————————",
"Nome operacional: Amelia B. Cole",
"Status: EXTRAÍDA",
"<br>",
"MOTIVO DA EXTRAÇÃO",
"——————————————————",
"→ Conspiração contra o Estado",
"→ Envolvimento com grupos progressistas subversivos",
"→ Participação em cultos extorroristas",
"<br>",
"ANOTAÇÕES DO CASO",
"——————————————————",
"Extração realizada com êxito. Sujeito não retém memórias de vida anterior.",
"Relocada sob nova identidade designada pelo DEMP.",
"Ocupação de cobertura: Professora Universitária — IFSP, Câmpus Cotia (SP).",
"Local de residência atual: Cutias, interior do Amapá.",
"Rede de suporte: Integralmente composta por Agentes DEMP disfarçados",
"(parentes, amigos e colegas de trabalho).",
"<br>",
" DIRETIVA ATUAL",
"——————————————————",
"Qualquer indício de recuperação de memória ou comportamento anti-cidadão",
"resultará em aplicação imediata da Diretiva 7 — TÉRMINO.",
"<br>",
"██████████████████████████████████████████",
"Para acessar registros completos, digite:",
"[SOBRENOME DO AGENTE] Log [NÚMERO]",
"Exemplo: Souza Log0001",
"██████████████████████████████████████████",
"</br>"
]

Log01=[
"<br>",
"██████████████████████████████████████████",
"		      REGISTRO 0001-14/10/1974		   ",
"██████████████████████████████████████████",
"Agentes do DEMP invadiram a casa de Camila Botelho durante a madrugada de hoje, os agentes fizeram uma",
"cópia da casa da pesquisadora, a pesquisadora rapidamente foi anestesiada e levada até o prédio do DEMP",
"onde foi deixada em uma sela reservada temporariamente.",
"Nenhum rastro foi deixado durante essa operação e as autoridades locais acreditam que não houve arrombamento",
"na casa.",
"Entretanto esse súbito desaparecimento da pesquisa, levantou fortes debates e revolta entre os grupos progressistas",
"que Camila frequentava",
"██████████████████████████████████████████",
"		        FIM DE REGISTRO                ",
"██████████████████████████████████████████",
]

Log02=[
"<br>",
"██████████████████████████████████████████",
"		        REGISTRO 0002-04/11/1974		   ",
"██████████████████████████████████████████",
"Foi Iniciado o processo de Extração, Camila Botelho por   ",
"seu envolvimento com grupos progressistas não poderá passar",
"pelo processo formal de integração de agentes.",
"Camila passará pelo processo de renascimento, seus novos",
"documentos, local de trabalho, casa, amigos, familiares e",
"colegas de trabalho já estão em processo de encaminhamento",
"acredita-se que no próximo mês a pesquisadora poderá começar",
"sua nova vida",
"██████████████████████████████████████████",
"		      FIM DE REGISTRO                      ",
"██████████████████████████████████████████",
"</br>"
]

Log03=[
"<br>",
"██████████████████████████████████████████",
"		         REGISTRO 0003-11/11/1974		   ",
"██████████████████████████████████████████",
"Finalizado o processo de extração, a pesquisadora não apresenta",
"nenhuma sequela significativa, e nenhum resquício de sua antiga",
"vida parece ainda existir dentro da sua mente, Camila agora está",
"passando pelo processo de reabilitação com o falso pretexto de",
"ter sofrido um acidente de carro enquanto ia para o trabalho.",
"██████████████████████████████████████████",
"		      FIM DE REGISTRO                      ",
"██████████████████████████████████████████",
"</br>"
]

Log04=[
"<br>",
"██████████████████████████████████████████",
"		         REGISTRO 0004-11/12/1974		   ",
"██████████████████████████████████████████",
"Amelia B. Cole, antiga Camila Botelho, apresentou um comportamento exemplar durante o processo de reabilitação,",
"ela se adaptou rapidamente a sua nova vida, e não apresentou nenhum comportamento anti-cidadão ou indício de",
"recuperação de memória, Amelia agora está passando por um processo de monitoramento, onde seus comportamentos",
"são monitorados constantemente por agentes disfarçados, para garantir que a diretiva 7 seja cumprida",
"qualquer caso de recuperação de memória ou comportamento anti-cidadão resultará na aplicação imediata da diretiva 7, que é o término do sujeito",
"██████████████████████████████████████████",
"		      FIM DE REGISTRO                      ",
"██████████████████████████████████████████",
"</br>"
]

// ── SEQUÊNCIA DE BOOT ──────────────────────────────────────────────────
bootSequence = [
"Initializing DEMP Kernel v.3.7-classified... OK",
"Loading Security Abstraction Layer... OK",
"Verifying Agent Database... 1.847 records",
"Verifying Ex-Citizen Database... 342 records",
"────────────────────────────────────────────────────",
"Establishing connection to DEMP/BRS-01...",
  "Resolving host: 192.168.15.7 ... OK",
  "Opening socket on port 4433 (TLS) ... OK",
  "Awaiting server response ... OK",
  "Certificate fingerprint: 9F:3A:C1:04:BE:72:DA:9E:11:08:CC:47:F3",
  "Tunnel established — Latency: 14ms — Uplink: 512 kbps",
"Connection to DEMP/BRS-01... ESTABLISHED",
"────────────────────────────────────────────────────",
"Authenticating Administrator credentials...",
  "Sending token [RSA-4096] ... OK",
  "Access level verified: ADMINISTRADOR",
"Authentication... GRANTED",
"────────────────────────────────────────────────────",
"Synchronizing internal clock... 00:00:01 — 1974",
"System integrity check... PASSED",
"DEMP Terminal ready.",
];

banner = [
"██████╗ ███████╗███╗   ███╗██████╗ ",
"██╔══██╗██╔════╝████╗ ████║██╔══██╗",
"██║  ██║█████╗  ██╔████╔██║██████╔╝",
"██║  ██║██╔══╝  ██║╚██╔╝██║██╔═══╝ ",
"██████╔╝███████╗██║ ╚═╝ ██║██║   ",  
"╚═════╝ ╚══════╝╚═╝     ╚═╝╚═╝  ",
"DEPARTAMENTO DE EXTERMÍNIO DE",
"MANIFESTAÇÕES PARANORMAIS",   
  '<span class="color2">Bem vindo <i>Administrador</i></span>',
  "<span class=\"color2\">Digite o nome do Agente ou Ex-Cidadão para saber <i>mais<i></span><span class=\"color2\">.</span>",
];